apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainui
spec:
  selector:
    matchLabels:
      app: mainui
  template:
    metadata:
      labels:
        app: mainui
    spec:
      serviceAccountName: ${serviceaccount}
      containers:
      - image: ${registryprefix}/${project}/${project}/adminapp:v0.4.0
        imagePullPolicy: Always
        name: mainui
        ports:
        - containerPort: 8000
        env: 
        - name: CONFLUENT_KEY_NAME # these are dummies at the moment
          value: confluent-api-key
        - name: CONFLUENT_SECRET_NAME # these are dummies at the moment
          value: confluent-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mainui
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: ClusterIP 
  selector:
    app: mainui
