apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: server-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: none
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: ${data_center}
  #namespace: default
spec:
  clusterName: ${cluster_name}
  serverType: cassandra
  serverVersion: 3.11.7
  superuserSecretName: ${secret}
  managementApiAuth:
    insecure: {}
  size: 1
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: server-storage
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  config:
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: 800M
      max_heap_size: 800M

## TODO!! This should NOT be needed

# GKE automatically assigns in-cluster dns: my-svc.my-namespace.svc.my-zone
# in this case, this would be dc1.mainspark.CassandraDatacenter.us-central1
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: cassandraservice
#   labels:
#     cassandra.datastax.com/cluster: cluster1
#     cassandra.datastax.com/datacenter: dc1
#     cassandra.datastax.com/rack: default
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 9042
#     protocol: TCP
#   selector:
#     cassandra.datastax.com/cluster: cluster1
#     cassandra.datastax.com/datacenter: dc1
#     cassandra.datastax.com/rack: default
