apiVersion: networking.k8s.io/v1beta1 # extensions/v1beta1
kind: Ingress
metadata:
  name: streamstateingress
  # namespace: argo-events
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: streamstate-global-ip
    networking.gke.io/managed-certificates: certificate-name-new
    networking.gke.io/v1beta1.FrontendConfig: ingress-security-config
    # https://github.com/argoproj/argo-workflows/blob/master/docs/argo-server.md#ingress
    ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: streamstateingress
spec:
 
  backend: # default
    serviceName: argo-server
    servicePort: 2747
  rules:
    - http:
        paths:
        - path: /ui/*
          backend:
            serviceName: argo-server
            servicePort: 2747
        - path: /build/*
          backend:
            serviceName: argowebhook
            servicePort: 12000
        - path: /monitoring/*
          backend:
            serviceName: prometheus-server 
            servicePort: 9091
        - path: /grafana/*
          backend:
            serviceName: grafana
            servicePort: 3001
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: certificate-name-new
  # namespace: argo-events
spec:
  domains:
   - testorg.streamstate.org 

---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: ingress-security-config
  # namespace: argo-events
spec:
  # sslPolicy: gke-ingress-ssl-policy
  redirectToHttps:
    enabled: true