apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-config
  # namespace: argo-events
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: cookie-secret
data: 
  client-id: ${client_id} 
  client-secret: ${client_secret}
  oidc-issuer-url: aHR0cHM6Ly9kZXYtMjA0OTAwNDQub2t0YS5jb20vb2F1dGgyL2RlZmF1bHQ= # placeholder to own url
  extra-jwt-issuers: aHR0cHM6Ly9kZXYtMjA0OTAwNDQub2t0YS5jb20vb2F1dGgyL2RlZmF1bHQ9YXBpOi8vZGVmYXVsdA== # placeholder to own extra issuer