apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-config
  # namespace: argo-events
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: cookie-secret
data: 
  # python -c 'import os,base64; print(base64.urlsafe_b64encode(os.urandom(16)).decode())'
  # cookie_secret:
  client-id: ${client_id}
  client-secret: ${client_secret}