apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-config
  # namespace: argo-events
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: cookie-secret
data: 
  client-id: placeholder
  client-secret: placeholder
  oidc-issuer-url: placeholder
  extra-jwt-issuers: placeholder
  #client-id: ${client_id}
  #client-secret: ${client_secret}