### ingress gets redirected here on auth
config:
  existingSecret: oauth2-proxy-config
  configFile: |-
    email_domains = [ "*" ]
    upstreams = [ 
      "argo-server.serviceplane-${organization}.svc.cluster.local",
      "prometheus-server.serviceplane-${organization}.svc.cluster.local",
      "grafana.serviceplane-${organization}.svc.cluster.local"
    ]
  #  oidc_issuer_url = https://dev-20490044.okta.com/oauth2/default
  #  reverse_proxy=true
extraArgs:
  whitelist-domain: .streamstate.org
  cookie-domain: .streamstate.org
  provider: oidc
  oidc-issuer-url: https://dev-20490044.okta.com/oauth2/default
  reverse-proxy: true
  pass-access-token: true
  skip-provider-button: true
  exclude-logging-path: true
  pass-host-header: true
#authenticatedEmailsFile:
  #enabled: true
  #restricted_access: |-
  #  allowed@user1.com
  #  allowed@user2.com
image:
  tag: "v7.1.3"
ingress:
  enabled: true
  path: /
  hosts:
    - ${organization}.streamstate.org
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  tls:
    - secretName: streamstate-oauth-cert
      hosts:
        - ${organization}.streamstate.org


       