---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: prometheus
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 9091
    type: HTTP
    requestPath: /ping
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: grafana
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 3001
    type: HTTP
    requestPath: /ping