service:
  type: NodePort
  port: 3000
  targetPort: 3000

# https://grafana.com/tutorials/run-grafana-behind-a-proxy/
# gateway/ingress.yml
grafana.ini:
  auth.anonymous:
      enabled: true
  server:
    server:
    domain: ${organization}.streamstate.org 
    root_url: https://${organization}.streamstate.org/grafana/
    serve_from_sub_path: true
datasources: 
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.serviceplane-${organization}.svc.cluster.local:9090/prometheus
      access: proxy
      isDefault: true
rbac:
  namespaced: true