service:
  type: NodePort
  port: 3000
  targetPort: 3000

# https://grafana.com/tutorials/run-grafana-behind-a-proxy/
# gateway/ingress.yml
grafana.ini:
  auth:
    anonymous:
      enabled: true
  server:
    serve_from_sub_path: true
    root_url: https://testorg.streamstate.org/grafana

rbac:
  namespaced: true