apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-argo
  namespace: ${monitoringnamespace}
  labels:
    release: prometheus # to connect back to main prometheus "hub"
spec:
  namespaceSelector:
    matchNames: 
      - ${operatornamespace}
  selector:
    matchLabels:
      app: argo
  endpoints:
  - targetPort: 10254 # todo, change 

---
apiVersion: v1
kind: Service
metadata:
  name: spark-svc-argo
  namespace: ${operatornamespace}
  labels:
    app: argo
spec:
  ports:
    - name: metrics-argo
      port: 10254
      targetPort: 10254
      protocol: TCP
  selector:
    deployment.kubernetes.io/name: workflow-controller 