apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
spec:
  sparkConf:
    spark.jars.packages: "org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.0"
    spark.jars.repositories: "https://packages.confluent.io/maven"
    spark.jars.ivy: "/tmp/ivy"
  type: Scala
  mode: cluster
  imagePullPolicy: Never
    
  mainClass: sparkwrappers.KafkaSourceWrapper
  mainApplicationFile: "local:///opt/spark/work-dir/sparkstreaming.jar"
  sparkVersion: "3.0.1"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp" # todo, point to object storage
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.1
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp" # todo, point to object storage
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.1
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp" # todo, point to object storage
