apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    native:
      # Optional, defaults to 3. If it is < 3, set it to 3, that is the minimal requirement.
      replicas: 3
      # Optional, authen strategy, "none" or "token", defaults to "none"
      auth: token
#      containerTemplate:
#        resources:
#          requests:
#            cpu: "10m"
#      metricsContainerTemplate:
#        resources:
#          requests:
#            cpu: "10m"
#      antiAffinity: false
#      persistence:
#        storageClassName: standard
#        accessMode: ReadWriteOnce
#        volumeSize: 10Gi

---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: streamstatewebservice
  labels:
    eventsource: streamstate
spec:
  # replicas: 3 # needed for HA
  #selector:
  #  matchLabels:
  #    app: argobackend
  #service:  # TODO, get more robust service
  #  ports:
  #    - port: 12000
  #      targetPort: 12000
  webhook:
    # event-source can run multiple HTTP servers. Simply define a unique port to start a new HTTP server
    runcontainer:
      # port to run HTTP server on
      port: "12000"
      # endpoint to listen to
      endpoint: /build/container
      # HTTP request method to allow. In this case, only POST requests are accepted
      method: POST
    example:
      # port to run HTTP server on
      port: "12000"
      # endpoint to listen to
      endpoint: /build/example
      # HTTP request method to allow. In this case, only POST requests are accepted
      method: POST
    readiness:
      # port to run HTTP server on
      port: "12000"
      # endpoint to listen to
      endpoint: /
      method: GET
      #authSecret:
      #  name: my-webhook-token
      #  key: my-token
#    example-foo:
#      port: "12000"
#      endpoint: /example2
#      method: POST

# Uncomment to use secure webhook
#    example-secure:
#      port: "13000"
#      endpoint: "/secure"
#      method: "POST"
#      # k8s secret that contains the cert
#      serverCertSecret:
#        name: my-secret
#        key: cert-key
#      # k8s secret that contains the private key
#      serverKeySecret:
#        name: my-secret
#        key: pk-key

# ---        
# apiVersion: v1
# kind: Service
# metadata:
#   name: argoeventsservice
#   #namespace: default
# spec:
#   type: NodePort
#   selector:
#     app: argobackend
#   ports:
#   - port: 80
#     targetPort: 12000
#     protocol: TCP
#---
#apiVersion: networking.k8s.io/v1beta1
#kind: Ingress
#metadata:
#  name: espv2
#spec:
#  backend:
#    serviceName: espv2 # Name of the Service targeted by the Ingress
#    servicePort: 80 # Should match the port used by the Service
---
apiVersion: v1
kind: Service
metadata:
  name: argowebhook
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - port: 80
    targetPort: 12000
    protocol: TCP
    name: http
  #selector:
  #  eventsource: streamstate
  type: NodePort 
  selector:
    controller: eventsource-controller
    eventsource-name: streamstatewebservice
    # owner-name: webhook
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argoingress
  annotations:
    # If the class annotation is not specified it defaults to "gce".
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: ${staticipname} # streamstate-global-ip # defined in gke.tf, TODO add this as output variable from gke.tf instead of hardcoding
spec:
  backend:
    serviceName: argowebhook
    servicePort: 80
  rules:
  - 
    http:
      paths:
      - path: /* # todo, make this /[organization]/.  I think we need to go with one k8s cluster
        backend:
          serviceName: argowebhook
          servicePort: 80
    # host: streamstate.org
      #- path: /ui # how will this work with ssl?
      #  backend: 
      #    serviceName: argo-server 
      #    servicePort: 2746 
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: certificate-name
spec:
  domains:
    - streamstate.org # manually confgured A records to point to static ip
