apiVersion: apps/v1
kind: Deployment
metadata:
  name: managek8s
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: managek8s-site
        image: us.gcr.io/streamstatetest/streamstaterest:v0.2.0
        envFrom:
        - secretRef:
            name: "spark-secret-basic" # pass in from spark-secret credentials
        #imagePullPolicy: Never # ensure going to  local docker registry and not docker.io
---
apiVersion: v1
kind: Service
metadata:
  name: bb-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001