apiVersion: v1
kind: Service
metadata:
  name: example-app-service
  labels:
    sparkoperator.k8s.io/app-name: devfromfile
spec:
  ports:
  - name: web
    port: 8090
    targetPort: 8090
    protocol: TCP
  selector:
    sparkoperator.k8s.io/app-name: devfromfile