apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: 3.11.7
  # hostNetwork: true # may need to adjust this depending on kubernetes environment, see https://docs.datastax.com/en/cass-operator/doc/cass-operator/cassOperatorConnectToK8sFromOutsideCluster.html
  #networking: # https://docs.datastax.com/en/cass-operator/doc/cass-operator/cassOperatorProvisioning.html
  #  nodePort:
  #    cql: 30001
  #    broadcast: 30002
  managementApiAuth:
    insecure: {}
  size: 1 # obviously increase this for production
  #allowMultipleNodesPerWorker: true # turn this off in production
  #resources:
  #  requests:
  #    memory: 60Mi
  #    cpu: 100m
  #  limits:
  #    memory: 60Mi
  #    cpu: 100m
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: standard # this comes with minikube; but will want something different in real deployment
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
  config:
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: "800M"
      max_heap_size: "800M"
      additional-jvm-opts:
        # As the database comes up for the first time, set system keyspaces to RF=3
        - "-Ddse.system_distributed_replication_dc_names=dc1"
        - "-Ddse.system_distributed_replication_per_dc=3"