apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: streamstatecert
  namespace: gloo-system #cert-manager # does this need to be in a certain namespace?
spec:
  dnsNames:
    - streamstate.org
  secretName: letsencrypt-staging # is this prviateKeySecretRef?
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging