apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi
spec:
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      serviceAccountName: ${firestoreviewer}
      containers:
      - image: ${registryprefix}/${project}/${project}/restapi:v0.0.3
        imagePullPolicy: Always
        name: restapi
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000" 
        - name: NAMESPACE 
          value: ${namespace}
        - name: SERVICE_NAMESPACE
          value: ${servicenamespace}
        envFrom:
          - configMapRef:
              name: ${dataconfigargo}
---
apiVersion: v1
kind: Service
metadata:
  name: restapi
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: ClusterIP 
  selector:
    app: restapi